adding Capture 2 with EasyLink
hacf-fr/hassRenaultZE pull request #73
Opened 2020-11-12 16:08 UTC by chino-lu

- added the Captur 2 to support location
- added Fuel Range sensor to support Renault vehicles with a thermal engine
- renamed range to battery range do make the difference clear

2020-11-12 16:24 UTC, epenet reviewed
This is great @chino-lu 

Can you please add an issue/comment on https://github.com/hacf-fr/renault-api/ to show a sample from your mileage DEBUG output?

2020-11-12 16:24 UTC, epenet commented on custom_components/renault/sensor.py
> +    entities.append(RenaultRangeBatterySensor(vehicle_proxy, "Battery Range"))
Can you make use of MODEL_USES_FUEL here to create either the battery OR the fuel sensor?

2020-11-12 16:24 UTC, epenet commented on custom_components/renault/sensor.py
>      """Range sensor."""
Update the description.
```suggestion
    """Battery Autonomy sensor."""
```

2020-11-12 18:59 UTC, epenet commented
Hi @chino-lu, I think there are some confusions here in your latest changes.

In `pyzevehicleproxy.py` you do not need MODEL_USES_KWH (this is used to differentiate between electric vehicles reporting power as KWH or WH.
You should instead use MODEL_USES_FUEL to differentiate between electric vehicles and non-electric vehicles

```
if self.model_code not in MODEL_USES_FUEL:
    self.coordinators["battery"] ....
    self.coordinators["charge_mode"] ...
else:
    LOGGER.warning("Model code %s does not support battery information.", self.model_code)
```

`mileage` and `hvac_status` (air conditionning) coordinators are available on both electric and non-electric vehicles. so shouldn't be dependant on MODEL_USES_FUEL or MODEL_SUPPORTS_LOCATION

In `sensor.py` all the ATTR_ constants and Renault____Sensor classes should always get created. You only need to change the conditions in `get_vehicle_entities`

2020-11-12 20:29 UTC, chino-lu commented
ok thanks, I had not yet seen the hvac status working, will try this out

2020-11-13 20:35 UTC, epenet commented
Please keep the hvac_status active anyway in the code, and disable it inside HA front-end.
We need to find a "proper" way to check if hvac_status is available or not. I don't think model code is the correct way to do this check.

2020-11-19 16:14 UTC, epenet commented
@chino-lu if you have time, can you please open a PR on https://github.com/hacf-fr/renault-api with two sample files?

https://github.com/hacf-fr/renault-api/tree/develop/tests/fixtures/kamereon/vehicles (captur2.1.json)
https://github.com/hacf-fr/renault-api/tree/develop/tests/fixtures/kamereon/vehicles (cockpit.1.json)

We are in process of phasing out the use of PyZE and the more samples we have the better the new API will be.

Cheers,

2020-11-19 20:49 UTC, chino-lu commented
unfortunately I don't get it up und running and the documentation is also not very completed

2020-11-20 07:58 UTC, epenet commented
For now, you can just copy-paste the traces from HomeAssistant if you enable debug there:
```
logger:
  default: error
  logs:
    pyze: debug
    custom_components.renault: debug
```

Or use PyZE module to generate the traces.

2020-11-30 11:37 UTC, epenet commented
@chino-lu do you want to try the latest custom component from this branch?
https://github.com/hacf-fr/hassRenaultZE/tree/renault-api

It should have "Fuel Quantity" and "Fuel Autonomy" added.

2020-12-04 14:42 UTC, epenet commented
@chino-lu can you please test with [release v3.0.2](https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.2) and confirm it's working as expected?

2020-12-04 18:46 UTC, chino-lu commented
@epenet yes, will try during the weekend... unfortunately not a lot of time at the moment to work on this

2020-12-06 08:43 UTC, chino-lu commented
only get one error in the log

`Logger: custom_components.renault.renault_vehicle
Source: helpers/update_coordinator.py:166
Integration: Renault (documentation, issues)
First occurred: 9:40:24 (1 occurrences)
Last logged: 9:40:24

Error fetching VF1RJB00465328290 hvac_status data: This endpoint has been disabled: ('err.func.403', 'Operation not supported Operation not supported for this can (C1A)')`

2020-12-06 11:07 UTC, epenet commented
I'll change that to a warning in the next release.

2020-12-06 20:17 UTC, tetienne requested changes

2020-12-06 20:17 UTC, tetienne commented on custom_components/renault/sensor.py
> +if self.model_code in MODEL_USES_KWH:
What's the point to of this condition? That's unusual to avoid class declaration.

2020-12-06 20:17 UTC, tetienne commented on custom_components/renault/sensor.py
> +            attrs = {}
You can avoid this. The line just after you initialize again.

2020-12-06 20:17 UTC, tetienne commented on custom_components/renault/sensor.py
> +            LOGGER.warning("batteryLevel not available in coordinator data %s", data)
Here you forgot the return None, line 147 you did it.

2020-12-06 20:17 UTC, tetienne commented on custom_components/renault/sensor.py
> +                else:
This else is useless as you do a return in the if.

2020-12-06 20:17 UTC, tetienne commented on custom_components/renault/sensor.py
> +            if not self.hass.config.units.is_metric:
You can avoid this not if you switch the returns.

2020-12-06 20:17 UTC, tetienne commented on custom_components/renault/sensor.py
> +            if not self.hass.config.units.is_metric:
Same remark

2020-12-16 09:45 UTC, epenet commented
@tetienne I have opened a separate PR for your recommendations.
I will close this one as it has been implemented in https://github.com/hacf-fr/hassRenaultZE/releases/tag/v3.0.2.

2020-12-16 09:45 UTC, closed without merging